const data = {
  products: [
    {
      name: 'Modern Green Sofa',
      slug: 'modern-green-sofa',
      category: 'Living Room',
      image: '/images/product1.jpg',
      price: 2.999,
      brand: 'Moderna',
      rating: 4.5,
      numReviews: 8,
    },
    {
      name: 'Upholstered Sofa',
      slug: 'upholstered-sofa',
      category: 'Living Room',
      image: '/images/product2.jpg',
      price: 1.999,
      brand: 'Silverline',
      rating: 4.7,
      numReviews: 14,
    },
    {
      name: 'Modern Accent Chair',
      slug: 'modern-accent-chair',
      category: 'Living Room',
      image: '/images/product6.jpg',
      price: 1.399,
      brand: 'Moderna',
      rating: 4.6,
      numReviews: 29,
    },
    {
      name: 'Accent Chair Sets',
      slug: 'accent-chair-set',
      category: 'Living Room',
      image: '/images/product7.jpg',
      price: 2.999,
      brand: 'Dreamboat',
      rating: 4.0,
      numReviews: 80,
    },
    {
      name: 'Dark Brown Accent Chair',
      slug: 'accent-chair',
      category: 'Living Room',
      image: 'images/product10.jpg',
      price: 1.799,
      brand: 'Moderna',
      rating: 4.8,
      numReviews: 6,
    },
  ],
};
export default data;
