import bcrypt from 'bcryptjs';

const data = {
  //Admin User
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    // Quest User
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Modern Green Sofa',
      slug: 'modern-green-sofa',
      category: 'living room',
      image: '/images/product1.jpg',
      price: 2999,
      brand: 'Moderna',
      rating: 3.4,
      numReviews: 17,
      countInStock: 20,
    },

    {
      name: 'Upholstered Sofa',
      slug: 'upholstered-sofa',
      category: 'living room',
      image: '/images/product2.jpg',
      price: 1999,
      brand: 'Silverline',
      rating: 4.7,
      numReviews: 14,
      countInStock: 10,
    },
    {
      name: 'Modern Accent Chair',
      slug: 'modern-accent-chair',
      category: 'living room',
      image: '/images/product6.jpg',
      price: 1399,
      brand: 'Moderna',
      rating: 4.6,
      numReviews: 29,
      countInStock: 20,
    },
    {
      name: 'Accent Chair Sets',
      slug: 'accent-chair-set',
      category: 'living room',
      image: '/images/product7.jpg',
      price: 2999,
      brand: 'Dreamboat',
      rating: 4.0,
      numReviews: 80,
      countInStock: 4,
    },
    {
      name: 'Dark Brown Accent Chair',
      slug: 'accent-chair',
      category: 'living room',
      image: '/images/product10.jpg',
      price: 1799,
      brand: 'Moderna',
      rating: 4.8,
      numReviews: 6,
      countInStock: 25,
    },
    {
      name: 'Colorful Accent Chair',
      slug: 'color-accent-chair',
      category: 'living room',
      image: '/images/product4.jpg',
      price: 599,
      brand: 'Moderna',
      rating: 4.2,
      numReviews: 12,
      countInStock: 8,
    },
    {
      name: 'Contemporary Modern Accent Chair set',
      slug: 'Accent-Chair',
      category: 'home office',
      image: '/images/product9.jpg',
      price: 1999,
      brand: 'Moderna',
      rating: 5.0,
      numReviews: 1,
      countInStock: 10,
    },
    {
      name: 'Black Dining Table with White Chairs',
      slug: 'Dinner-table-set',
      category: 'dining room',
      image: '/images/product8.jpg',
      price: 3999,
      brand: 'Moderna',
      rating: 4.0,
      numReviews: 29,
      countInStock: 29,
    },
    {
      name: 'Modern Gray 3 Pieces Living Room Set ',
      slug: 'modern-livingroom2-set',
      category: 'living room',
      image: '/images/banner2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 19999,
      brand: 'Moderna',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
    },
    {
      name: 'Dark Gray 4 Seater Sofa ',
      slug: 'gray-sofa-set',
      category: 'living room',
      image: '/images/banner3.jpg',
      isFeatured: true,
      featuredImage: '/images/banner3.jpg',
      price: 10999,
      brand: 'Moderna',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
    },
    {
      name: 'Chic Blush Pink 3 Pieces Living Room Set ',
      slug: 'modern-livingroom-set',
      category: 'living room',
      image: '/images/banner.jpg',
      isFeatured: true,
      featuredImage: '/images/banner.jpg',
      price: 12999,
      brand: 'Moderna',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
    },
  ],
};
export default data;
