import bcrypt from 'bcryptjs';

const data = {
  //Admin User
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    // Quest User
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Modern Green Sofa',
      slug: 'modern-green-sofa',
      category: 'Living Room',
      image: '/images/product1.jpg',
      price: 2.999,
      brand: 'Moderna',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
    {
      name: 'Upholstered Sofa',
      slug: 'upholstered-sofa',
      category: 'Living Room',
      image: '/images/product2.jpg',
      price: 1.999,
      brand: 'Silverline',
      rating: 4.7,
      numReviews: 14,
      countInStock: 10,
    },
    {
      name: 'Modern Accent Chair',
      slug: 'modern-accent-chair',
      category: 'Living Room',
      image: '/images/product6.jpg',
      price: 1.399,
      brand: 'Moderna',
      rating: 4.6,
      numReviews: 29,
      countInStock: 20,
    },
    {
      name: 'Accent Chair Sets',
      slug: 'accent-chair-set',
      category: 'Living Room',
      image: '/images/product7.jpg',
      price: 2.999,
      brand: 'Dreamboat',
      rating: 4.0,
      numReviews: 80,
      countInStock: 4,
    },
    {
      name: 'Dark Brown Accent Chair',
      slug: 'accent-chair',
      category: 'Living Room',
      image: '/images/product10.jpg',
      price: 1.799,
      brand: 'Moderna',
      rating: 4.8,
      numReviews: 6,
      countInStock: 25,
    },
    {
      name: 'Colorful Accent Chair',
      slug: 'color-accent-chair',
      category: 'Living Room',
      image: '/images/product4.jpg',
      price: 599,
      brand: 'Moderna',
      rating: 4.2,
      numReviews: 12,
      countInStock: 8,
    },
    {
      name: 'Contemporary Modern Orange Sofa',
      slug: 'sofa-set',
      category: 'Living Room',
      image: '/images/product11.jpg',
      price: 3.999,
      brand: 'Moderna',
      rating: 5.0,
      numReviews: 1,
      countInStock: 10,
    },
    {
      name: 'Green Leather Accent Chair 37.5',
      slug: 'green-accent-chair',
      category: 'Living Room',
      image: '/images/product12.jpg',
      price: 1.799,
      brand: 'Moderna',
      rating: 4.0,
      numReviews: 29,
      countInStock: 29,
    },
  ],
};
export default data;
